# Generated by Django 4.0.3 on 2022-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default=0.0, max_length=100)),
                ('panel_area', models.CharField(default=0.0, max_length=100)),
                ('solar_radiation', models.CharField(default=0.0, max_length=100)),
                ('efficiency', models.CharField(default=0.0, max_length=100)),
                ('performance_ratio', models.CharField(default=0.0, max_length=100)),
                ('turbine_cp', models.CharField(default=0.0, max_length=100)),
                ('pole_height', models.CharField(default=0.0, max_length=100)),
                ('turbine_radius', models.CharField(default=0.0, max_length=100)),
                ('air_density', models.CharField(default=0.0, max_length=100)),
                ('velocity', models.CharField(default=0.0, max_length=100)),
                ('wind_hours', models.CharField(default=0.0, max_length=100)),
                ('turbine_cp_tide', models.CharField(default=0.0, max_length=100)),
                ('tide_range', models.CharField(default=0.0, max_length=100)),
                ('radius_turbine', models.CharField(default=0.0, max_length=100)),
                ('water_density', models.CharField(default=0.0, max_length=100)),
                ('mean_velocity', models.CharField(default=0.0, max_length=100)),
                ('tide_hours', models.CharField(default=0.0, max_length=100)),
                ('water_density_wave', models.CharField(default=0.0, max_length=100)),
                ('wave_height', models.CharField(default=0.0, max_length=100)),
                ('wave_period', models.CharField(default=0.0, max_length=100)),
                ('pto_efficiency', models.CharField(default=0.0, max_length=100)),
                ('wave_hours', models.CharField(default=0.0, max_length=100)),
                ('solar_energy', models.CharField(default=0.0, max_length=100)),
                ('swept_area_wind', models.CharField(default=0.0, max_length=100)),
                ('wind_energy', models.CharField(default=0.0, max_length=100)),
                ('swept_area_tide', models.CharField(default=0.0, max_length=100)),
                ('tidal_energy', models.CharField(default=0.0, max_length=100)),
                ('wave_energy', models.CharField(default=0.0, max_length=100)),
                ('solar_energy_loss', models.CharField(default=0.0, max_length=100)),
                ('wind_energy_loss', models.CharField(default=0.0, max_length=100)),
                ('tidal_energy_loss', models.CharField(default=0.0, max_length=100)),
                ('wave_energy_loss', models.CharField(default=0.0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('local_time', models.CharField(max_length=100)),
                ('radiation_surface', models.FloatField(default=0.0)),
            ],
        ),
    ]
