# Generated by Django 4.0.3 on 2022-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='energy_percent_tidal',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='energy_percent_wave',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='energy_percent_wind',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='enery_percent_solar',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_energy',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
