# Generated by Django 4.0.3 on 2022-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0003_rename_enery_percent_solar_calculation_energy_percent_solar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='solar_LCOE',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='solar_operational_years',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='solar_total_cost',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tide_LCOE',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tide_operational_years',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tide_total_cost',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wave_LCOE',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wave_operational_years',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wave_total_cost',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wind_LCOE',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wind_operational_years',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wind_total_cost',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
