# Generated by Django 4.0.3 on 2022-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0004_calculation_solar_lcoe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='Country',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
