# Generated by Django 4.0.3 on 2022-04-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0005_calculation_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='solar_total_cost',
            new_name='s_cost',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='tide_total_cost',
            new_name='t_cost',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='wave_total_cost',
            new_name='wa_cost',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='wind_total_cost',
            new_name='wi_cost',
        ),
    ]
