# Generated by Django 4.0.3 on 2022-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0006_rename_solar_total_cost_calculation_s_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='ci_value',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='solar_co2',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tide_co2',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_co2',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wave_co2',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='calculation',
            name='wind_co2',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
