# Generated by Django 4.0.3 on 2022-05-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0008_rename_tide_lcoe_calculation_tidal_lcoe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='air_density',
        ),
    ]
