# Generated by Django 4.0.3 on 2022-05-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compdss', '0009_remove_calculation_air_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='water_density',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='water_density_wave',
        ),
    ]
